name: Deploy to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install NPM dependencies and build frontend
      uses: actions/setup-node@v3
    - run: npm install
      working-directory: ./EmployeeWorkOrderManagment/src/main/frontend
    - run: npm run build
      working-directory: ./EmployeeWorkOrderManagment/src/main/frontend

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Maven package
      run: mvn clean package
      working-directory: ./EmployeeWorkOrderManagment

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Dashboard to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./EmployeeWorkOrderManagment/Dockerfile
        push: true
        tags: thereallukey/empworkorder:latest
      
